export const SET_RECIPES = "SET_RECIPES";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const SET_INGREDIENTS = "SET_INGREDIENTS";

export const SET_SEARCH_Q = "SET_SEARCH_Q";
export const SET_SEARCH_FUNCTION = "SET_SEARCH_FUNCTION";
export const SET_SEARCH_BADGES = "SET_SEARCH_BADGES";
